// <auto-generated />
namespace EF2CapasApiFluent.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class messi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(messi));
        
        string IMigrationMetadata.Id
        {
            get { return "202210201302181_messi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
